---
name: Deploy Documentation

on:
  workflow_call:

permissions:
  # Require the permissions to the read the content
  contents: read
  # Required to authenticate the Github API
  id-token: write
  # Required to write PR comments with the validation results
  pull-requests: write

env:
  NODE_VERSION: '24'

jobs:
  deploy:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build documentation
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
