---
name: Validate GitHub Workflows
on:
  workflow_call:

jobs:
  validate-workflows:
    name: Validate GitHub Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate GitHub Workflows
        run: |
          echo "Validating GitHub workflow files..."
          find .github/workflows -name "*.yml" -o -name "*.yaml" | while read -r file; do
            echo "Validating $file"
            # Basic YAML validation
            python3 -c "import yaml; yaml.safe_load(open('$file'))" || exit 1
          done
          echo "✓ All GitHub workflow files are valid"
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.x
          cache: true
      - name: Install Actionlint
        run: go install github.com/rhysd/actionlint/cmd/actionlint@latest
      - name: Run Actionlint
        id: actionlint
        run: actionlint .github/workflows/*.yml
