---
name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-release.yml@14fa0378853fce002f4893d538c0cfd4aff8dfda # main
    name: GitHub Release
    with:
      enable-cliff: true
