---
name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-release.yml@3989754d15d0991f1c960f68075d7c5efd7b1ba1 # main
    name: GitHub Release
    with:
      enable-cliff: true
