---
name: Trigger Workflow
on:
  workflow_dispatch:
    inputs:
      aws-account-id:
        description: "The AWS account ID to deploy to"
        required: true
        type: string

      aws-role:
        description: "The AWS role to assume"
        required: true
        type: string

      enable_plan:
        description: "Whether to run the plan step"
        required: false
        type: boolean
        default: false

      enable_apply:
        description: "Whether to run the apply step"
        required: false
        type: boolean
        default: false

      terragrunt-dir:
        description: "The directory to deploy to"
        required: false
        type: string
        default: "."

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  terraform:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terragrunt-plan-and-apply-aws.yml@main
    name: "Terragrunt (Plan: ${{ inputs.enable_plan }}, Apply: ${{ inputs.enable_apply }})"
    secrets:
      actions-id: "${{ secrets.ORG_ACTIONS_APP_ID }}"
      actions-secret: "${{ secrets.ORG_ACTIONS_APP_SECRET }}"
      github-token: ${{ secrets.REPO_GITHUB_TOKEN }}
      infracost-api-key: ${{ secrets.ORG_INFRACOST_API_KEY }}
    with:
      aws-account-id: ${{ inputs.aws-account-id }}
      aws-role: ${{ inputs.aws-role }}
      enable-private-access: true
      enable-terragrunt-apply: ${{ inputs.enable_apply }}
      enable-terragrunt-plan: ${{ inputs.enable_plan }}
      terragrunt-dir: ${{ inputs.terragrunt-dir }}
