---
name: Terragrunt
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "Makefile"
      - "README.md"
      - "scripts/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "Makefile"
      - "README.md"
      - "scripts/**"

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  terraform:
    uses: ./.github/workflows/terragrunt-plan-and-apply-aws.yml
    name: Plan and Apply
    secrets:
      actions-id: "${{ secrets.ORG_ACTIONS_APP_ID }}"
      actions-secret: "${{ secrets.ORG_ACTIONS_APP_SECRET }}"
      github-token: ${{ secrets.REPO_GITHUB_TOKEN }}
      infracost-api-key: ${{ secrets.ORG_INFRACOST_API_KEY }}
    with:
      aws-account-id: "148761643183"
      aws-role: lza-application-landing-zones
      enable-infracost: false
      enable-private-access: true
      enable-matrix: true
